// Image EDITING end to end, on the full 42-layer checkpoint.
//
// The reference image is GENERATED by this same plugin first, so the
// test is self-contained and the reference is in-distribution -- a
// synthetic checkerboard would exercise the plumbing but tell you
// nothing about whether the model can read it.
//
// What is actually under test is the one thing plumbing bugs break
// silently: does the reference image REACH the model? An edit path that
// built the prefix correctly but never spliced the embeddings in, or
// spliced them with the generation twin of the embedder, would still
// produce a plausible image -- just one that ignores the reference. So
// the checks are comparative:
//
//   * TWO DIFFERENT references, one prompt, one seed, must give
//     different images -- the only thing that varied is the reference;
//   * the edit must DIFFER from the reference (something happened);
//   * the edit must DIFFER from the same prompt without the reference;
//   * the edit must be deterministic.
//
// Note what is NOT checked: that the edit resembles its reference. The
// obvious pixel-correlation test does not work -- recolouring a subject
// and re-framing it are both legitimate edits, and either destroys the
// correlation. Measured here: the edit correlated with its own
// reference at +0.22 while an UNRELATED generation of the same subject
// managed +0.32.
//
// Gated on VPIPE_U15_TEST_MODEL_PATH. Loads ~35 GB.

#include "u15-backbone.h"
#include "u15-config.h"
#include "u15-generator.h"
#include "u15-image.h"
#include "u15-metal-ops.h"
#include "u15-prompt.h"
#include "u15-weights.h"

#include "apple-silicon/metal-compute/metal-compute.h"
#include "generative-models/weight-set.h"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

using vpipe::genai::WeightSet;
using vpipe::metal_compute::MetalCompute;

extern "C" const unsigned char u15_kernels_bf16_metallib[];
extern "C" const unsigned long u15_kernels_bf16_metallib_len;

namespace {

int g_fail = 0;
int g_ran  = 0;

void
check(bool ok, const std::string& what)
{
  std::printf("  [%s] %s\n", ok ? " OK " : "FAIL", what.c_str());
  ++g_ran;
  if (!ok) { ++g_fail; }
}

double
mean_abs(const std::vector<std::uint8_t>& a,
         const std::vector<std::uint8_t>& b)
{
  double d = 0.0;
  for (std::size_t i = 0; i < a.size(); ++i) {
    d += std::fabs((double)a[i] - (double)b[i]);
  }
  return d / (double)a.size();
}

// planar [3][H][W] u8 -> the channel-last RefImage the generator wants.
u15::RefImage
to_ref(const std::vector<std::uint8_t>& planar, int h, int w)
{
  u15::RefImage r;
  r.width = w;
  r.height = h;
  r.rgb.resize((std::size_t)w * h * 3);
  for (int y = 0; y < h; ++y) {
    for (int x = 0; x < w; ++x) {
      for (int c = 0; c < 3; ++c) {
        r.rgb[((std::size_t)y * w + x) * 3 + c] =
            planar[((std::size_t)c * h + y) * w + x];
      }
    }
  }
  return r;
}

void
write_ppm(const std::string& path, const std::vector<std::uint8_t>& planar,
          int h, int w)
{
  std::FILE* f = std::fopen(path.c_str(), "wb");
  if (f == nullptr) { return; }
  std::fprintf(f, "P6\n%d %d\n255\n", w, h);
  for (int y = 0; y < h; ++y) {
    for (int x = 0; x < w; ++x) {
      for (int c = 0; c < 3; ++c) {
        std::fputc(planar[((std::size_t)c * h + y) * w + x], f);
      }
    }
  }
  std::fclose(f);
}

}  // namespace

int
main()
{
  const char* p = std::getenv("VPIPE_U15_TEST_MODEL_PATH");
  if (p == nullptr || *p == '\0') {
    std::printf("SKIPPED: VPIPE_U15_TEST_MODEL_PATH unset -- this test "
                "did NOT run.\n");
    return 0;
  }
  MetalCompute mc(nullptr);
  if (!mc.valid()) {
    std::printf("SKIPPED: no usable Metal device. NOTHING was checked.\n");
    return 0;
  }
  if (!mc.register_metal_library(u15::kMetalLibBf16,
                                 u15_kernels_bf16_metallib,
                                 u15_kernels_bf16_metallib_len)) {
    std::printf("FAILED to register the metallib\n");
    return 1;
  }

  u15::U15Config cfg;
  std::string err;
  if (!u15::parse_config(p, &cfg, &err)) {
    std::printf("FAILED config: %s\n", err.c_str());
    return 1;
  }

  // 384x384 (12x12 = 144 image tokens), NOT 256.
  //
  // 256^2 is exactly the model's documented min_pixels (65536) and
  // exactly base_image_seq_len (64 tokens), and it generates BADLY
  // there -- a tiny subject on a mostly-empty canvas, reproducibly, at
  // 8 and at 30 steps. 384, 512 and 1024 all produce clean images
  // through the same code path, which is the argument that this is the
  // model's own lower boundary rather than a port defect: a resolution
  // bug does not switch off between 12x12 and 16x16 tokens while being
  // pixel-perfect at 32x32. Not proven against the reference
  // implementation, which would need a 36 GB torch run.
  int size = 384, steps = 8;
  if (const char* s = std::getenv("VPIPE_U15_TEST_SIZE")) {
    size = std::atoi(s);
  }
  if (const char* s = std::getenv("VPIPE_U15_TEST_STEPS")) {
    steps = std::atoi(s);
  }

  auto ws = WeightSet::open(p, nullptr);
  if (ws == nullptr) { std::printf("FAILED to open\n"); return 1; }
  u15::U15Weights::Options opt;
  auto w = u15::U15Weights::load(ws, &mc, cfg, opt, &err);
  check(w != nullptr, "all 42 layers bound" +
                          (err.empty() ? "" : " (" + err + ")"));
  if (w == nullptr) { return 1; }

  u15::MetalOps ops;
  if (!ops.init(&mc, &err)) {
    std::printf("FAILED MetalOps: %s\n", err.c_str());
    return 1;
  }
  auto bb = u15::U15Backbone::create(&ops, cfg, w.get(), &err);
  auto ip = u15::ImagePath::create(&ops, cfg, w.get(), &err);
  auto pr = u15::Prompt::load(p, nullptr, &err);
  if (bb == nullptr || ip == nullptr || pr == nullptr) {
    std::printf("FAILED to build the model layer: %s\n", err.c_str());
    return 1;
  }
  u15::Generator::Deps d;
  d.ops = &ops; d.weights = w.get(); d.backbone = bb.get();
  d.image = ip.get(); d.prompt = pr.get();
  auto gen = u15::Generator::create(d, cfg, &err);
  check(gen != nullptr, "generator");
  if (gen == nullptr) { return 1; }

  u15::GenParams gp;
  gp.width = gp.height = size;
  gp.steps = steps;
  gp.cfg_scale = 4.0;
  gp.timestep_shift = 3.0;
  gp.seed = 42;
  const std::vector<u15::RefImage> no_refs;

  std::printf("%dx%d, %d steps\n\n", size, size, steps);

  // ---- 1. a reference image, from this same plugin ------------------
  std::vector<std::uint8_t> base;
  {
    const auto t0 = std::chrono::steady_clock::now();
    const bool ok = gen->generate(
        "a red fox sitting in snow, photorealistic", no_refs, gp, &base,
        nullptr, &err);
    check(ok, "generated the reference image" +
                  (err.empty() ? "" : " (" + err + ")"));
    if (!ok) { return 1; }
    std::printf("       %.1f s\n", std::chrono::duration<double>(
        std::chrono::steady_clock::now() - t0).count());
  }
  const u15::RefImage ref = to_ref(base, size, size);

  // ---- 2. the same prompt with NO reference -------------------------
  //
  // The control. Same words, same seed, no image -- so any difference
  // between this and the edit is the reference doing something.
  const std::string edit_prompt = "make the fox bright blue";
  std::vector<std::uint8_t> t2i_only;
  {
    const bool ok = gen->generate(edit_prompt, no_refs, gp, &t2i_only,
                                  nullptr, &err);
    check(ok, "generated the no-reference control");
    if (!ok) { return 1; }
  }

  // ---- 3. the EDIT ---------------------------------------------------
  std::vector<std::uint8_t> edited;
  {
    const auto t0 = std::chrono::steady_clock::now();
    const bool ok = gen->generate(edit_prompt, {ref}, gp, &edited, nullptr,
                                  &err);
    check(ok, "edit ran" + (err.empty() ? "" : " (" + err + ")"));
    if (!ok) { return 1; }
    std::printf("       %.1f s (a reference image adds a prefill and "
                "lengthens every step's attention)\n",
                std::chrono::duration<double>(
                    std::chrono::steady_clock::now() - t0).count());
  }
  check(edited.size() == base.size(), "edit output is [3][H][W] u8");

  // ---- the check that actually settles it ---------------------------
  //
  // A SECOND, unrelated reference through the SAME prompt and the SAME
  // seed. Everything else about the two runs is identical -- the words,
  // the initial noise, the schedule -- so if the outputs differ, the
  // difference came from the reference image and nowhere else.
  //
  // This replaced a pixel-correlation check, which could not do the job:
  // the edit here recolours a fox and re-frames it, so it correlates
  // with its reference WORSE than an unrelated generation of the same
  // subject does. Correlation on pixels measures composition and colour,
  // and an edit is licensed to change both. Two references is the
  // question stated without a proxy.
  std::vector<std::uint8_t> other_ref;
  {
    const bool ok = gen->generate(
        "a stone lighthouse on a cliff at sunset, dramatic clouds",
        no_refs, gp, &other_ref, nullptr, &err);
    check(ok, "generated a second, unrelated reference");
    if (!ok) { return 1; }
  }
  std::vector<std::uint8_t> edited_other;
  {
    const bool ok = gen->generate(edit_prompt, {to_ref(other_ref, size, size)},
                                  gp, &edited_other, nullptr, &err);
    check(ok, "edit ran against the second reference");
    if (!ok) { return 1; }
  }

  const double d_refs = mean_abs(edited, edited_other);
  const double d_edit = mean_abs(edited, base);
  const double d_ctrl = mean_abs(edited, t2i_only);
  std::printf("\n       mean|edit(A) - edit(B)|  = %.1f u8   <- two "
              "references, same prompt+seed\n", d_refs);
  std::printf("       mean|edit(A) - ref A|    = %.1f u8\n", d_edit);
  std::printf("       mean|edit(A) - control|  = %.1f u8   <- same "
              "prompt, no reference\n\n", d_ctrl);

  check(d_refs > 20.0,
        "two DIFFERENT references give different images from one prompt "
        "and one seed -- the reference image reaches the model");
  check(d_edit > 3.0, "the edit actually CHANGED the reference");
  check(d_ctrl > 3.0,
        "the edit differs from the same prompt without a reference");

  // Determinism: the same inputs twice must give the same bytes. A
  // difference here would mean uninitialised scratch somewhere, which
  // would also make every comparison above meaningless.
  {
    std::vector<std::uint8_t> again;
    if (gen->generate(edit_prompt, {ref}, gp, &again, nullptr, &err)) {
      check(again == edited, "the edit is deterministic (same inputs -> "
                             "same bytes)");
    }
  }

  if (const char* out = std::getenv("VPIPE_U15_TEST_OUT")) {
    const std::string base_path(out);
    write_ppm(base_path + ".ref.ppm", base, size, size);
    write_ppm(base_path + ".edit.ppm", edited, size, size);
    write_ppm(base_path + ".ctrl.ppm", t2i_only, size, size);
    write_ppm(base_path + ".ref2.ppm", other_ref, size, size);
    write_ppm(base_path + ".edit2.ppm", edited_other, size, size);
    std::printf("       wrote %s.{ref,edit,ctrl,ref2,edit2}.ppm\n", out);
  }

  std::printf("\n%d checks, %d failed\n", g_ran, g_fail);
  return g_fail == 0 ? 0 : 1;
}
